version: '3.4'

services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 5000:5000
      - 5001:5001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
